name: main

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v31

      - name: Run checks
        run: nix flake check

      - name: Build
        run: |
         nix run .#build

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: main.pdf
